### ISSUE TITLE
🐟 ohm nom nom

### ISSUE THREAD

**Issue by plantarflex** [tw4204/susansijang_crawler#3]
![image](https://user-images.githubusercontent.com/31844264/126878190-6968bc22-a0d2-4973-ae6c-8ca925123d71.png)

I want this Taewan!!

It is here
https://github.com/tw4204/susansijang_crawler/blob/46d39e7e4c250790530c90c4e5e0a3c0a49b4439/source/const.py#L33

**Comment by tw4204** [comment]
sorry..
